### PR TITLE
Texture options

### LINKED ISSUE #24: Support mipmap texture filters
Currently only linear and nearest filters are supported for textures. WebGL also allows mipmap filters for MIN filter (GL_NEAREST_MIPMAP_NEAREST, GL_LINEAR_MIPMAP_NEAREST, GL_NEAREST_MIPMAP_LINEAR and GL_LINEAR_MIPMAP_LINEAR).

Using mipmaps can lead to better visual quality as the downscaled versions of a texture can be pre-filtered or even hand-manipulated, but can also lead to vastly better performance. For example, rendering a large texture many times (like a tiled pattern) ends up being slow because of the bandwidth overhead of each tile draw operation utilising the entire texture.

More details on the mipmap filters available to WebGL can be found here: https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameter.xml

I'm happy to submit a PR if this issue is accepted.

### PR DESCRIPTION
**Pull request by w0rm**
This closes #24

### CODE REVIEW

**Comment by w0rm** [comment]
I had to prefix `MagnifyingFilter` options with `magnify` because the names clash with `MinifyingFilter`. Even though they are the same things internally, the magnifying filter only allows two possible options, so I want to limit it with types.

**Comment by w0rm** [comment]
@Zinggi  @lepoetemaudit could you please have a look.

**Comment by lepoetemaudit** [comment]
It looks good to me - the level of the comments is really helpful for understanding how it corresponds to the WebGL equivalents, and I think all the defaults are very sensible. I'm guessing this pattern...

```elm
    Texture.loadWith
        { textureOptions
            | magnifyingFilter = Texture.magnifyNearest
            , minifyingFilter = Texture.nearest
        }
```

...means that if other textureOptions are added in future it will be backwards-compatible with older code. If so, I'm all in favour. I think there are quite a few other potential options that may need to be added in future (different source / target image formats for example).

Thanks for looking at this!

**Comment by w0rm** [comment]
@lepoetemaudit what do you think about prefixed `magnifyNearest` for  the magnifying  filter and unprefixed `nearest` for the minifying filter?

**Comment by lepoetemaudit** [comment]
@w0rm I agree with separating out the types. Perhaps we could prefix the minify, e.g. `minifyNearest`, for consistency? Personally I don't much mind either way.

**Comment by w0rm** [comment]
@lepoetemaudit I really don't know myself, I've considered this option, but then
`minifyNearestMipmapLinear` would be too long. Anyway, I renamed for the sake of consistency.

I also added `flipY` that is `True` by default, so it doesn't break existing shaders. The reasoning behind this is that it makes it a bit harder to map the coordinates to texture.

**Pull request merged**
