### PR TITLE
Added clear color function

### PR DESCRIPTION
**Pull request by w0rm**
Re-opening the original @mchav [pull request](https://github.com/elm-community/elm-webgl/pull/11) here.

I squashed commits and rebased the changes on top of current master.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
I see a lot of activity in this repo. Cool! I'm wondering, though, about the situation concerning Evan's constraints on the `webgl` package.

As expressed here: https://github.com/elm-lang/package.elm-lang.org/issues/149#issuecomment-171068020

And also discussed here: https://github.com/elm-community/elm-webgl/issues/6

If Evan is not in the loop, all the work you put into changes here might be for naught, in the sense that you would not be able to publish to the package site.

Maybe I'm concerned for nothing, and everything is agreed upon and sorted out. But just in case it is not, I'm raising this here.

**Comment by w0rm** [comment]
@jdavidberger I'm not merging anything. Only migrating the pull requests.

**Comment by jvoigtlaender** [comment]
Okay, cool. (Assuming the above comment is directed to me.)

I don't want to keep you from anything. Was just concerned whether you are aware of the earlier discussions.

**Comment by w0rm** [comment]
@jvoigtlaender I fully understand our limitations, I just don't want the work to be lost during the migration. I'm currently porting the relevant pull requests and labeling them with `major` or `minor` depending on the changes.

**Comment by jvoigtlaender** [comment]
Concerning the migration itself: Has Evan agreed to whitelist the new name? Otherwise, no publishing...

**Comment by w0rm** [comment]
@jvoigtlaender yeah, it has been [whitelisted](https://github.com/elm-lang/package.elm-lang.org/pull/206) and [published](http://package.elm-lang.org/packages/elm-community/webgl/latest).

**Comment by jvoigtlaender** [comment]
Great!

**Pull request merged**
